version: "3"
services:
  db:
    image: mongo
    env_file:
    - ./Docker/.env
    restart: always
    volumes:
    - ./db:/data/db
  node:
    image: node
    user: "node"
    working_dir: /home/node/app
    env_file:
    - ./Docker/.env
    environment:
    - NODE_ENV=development
    - DBHOST=db
    volumes:
    - ./server:/home/node/app
    ports:
    - "8000:8000"
    links:
    - db:db
    depends_on:
    - "db"
    command: "npm run watch"
