version: "3"
services:
  db:
    image: mongo
    env_file:
    - ./Docker/.env
    restart: always
    volumes:
    - ./db/mongo:/data/db
    - ./db/init:/docker-entrypoint-initdb.d
  server:
    image: node
    user: "node"
    working_dir: /home/node/app
    restart: always
    env_file:
    - ./Docker/.env
    environment:
    - NODE_ENV=development
    - DBHOST=db
    volumes:
    - ./server:/home/node/app
    ports:
    - "8000:8000"
    links:
    - db:db
    depends_on:
    - "db"
    command: "npm run watch"
  client:
    image: node
    working_dir: /home/node/app
    restart: always
    volumes:
    - ./client:/home/node/app
    ports:
    - "3000:3000"
    depends_on:
    - "server"
    command: "npm run start && npm run watch"
