CREATE TABLE shop (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name CHAR(50) NOT NULL
)

CREATE TABLE category (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name CHAR(50) NOT NULL
)

CREATE TABLE product (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name CHAR(50) NOT NULL,
  id_category INT
)

CREATE TABLE buy (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  id_shop INT NOT NULL,
  id_product INT NOT NULL,
  price FLOAT(5,2) NOT NULL,
  count SMALLINT NOT NULL
)
